// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

package web.api.rpc.follow;

public interface AddFollowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddFollowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
