// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

package web.api.rpc.follow;

public interface GetFollowingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFollowingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string following = 1;</code>
   */
  java.util.List<java.lang.String>
      getFollowingList();
  /**
   * <code>repeated string following = 1;</code>
   */
  int getFollowingCount();
  /**
   * <code>repeated string following = 1;</code>
   */
  java.lang.String getFollowing(int index);
  /**
   * <code>repeated string following = 1;</code>
   */
  com.google.protobuf.ByteString
      getFollowingBytes(int index);
}
