// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

package web.api.rpc.follow;

public interface GetFollowerAndFollowingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFollowerAndFollowingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
