// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

package web.api.rpc.follow;

/**
 * Protobuf type {@code GetFollowingResponse}
 */
public  final class GetFollowingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetFollowingResponse)
    GetFollowingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFollowingResponse.newBuilder() to construct.
  private GetFollowingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFollowingResponse() {
    following_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetFollowingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              following_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            following_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        following_ = following_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.api.rpc.follow.Follow.internal_static_GetFollowingResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.api.rpc.follow.Follow.internal_static_GetFollowingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.api.rpc.follow.GetFollowingResponse.class, web.api.rpc.follow.GetFollowingResponse.Builder.class);
  }

  public static final int FOLLOWING_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList following_;
  /**
   * <code>repeated string following = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFollowingList() {
    return following_;
  }
  /**
   * <code>repeated string following = 1;</code>
   */
  public int getFollowingCount() {
    return following_.size();
  }
  /**
   * <code>repeated string following = 1;</code>
   */
  public java.lang.String getFollowing(int index) {
    return following_.get(index);
  }
  /**
   * <code>repeated string following = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFollowingBytes(int index) {
    return following_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < following_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, following_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < following_.size(); i++) {
        dataSize += computeStringSizeNoTag(following_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFollowingList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.api.rpc.follow.GetFollowingResponse)) {
      return super.equals(obj);
    }
    web.api.rpc.follow.GetFollowingResponse other = (web.api.rpc.follow.GetFollowingResponse) obj;

    boolean result = true;
    result = result && getFollowingList()
        .equals(other.getFollowingList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFollowingCount() > 0) {
      hash = (37 * hash) + FOLLOWING_FIELD_NUMBER;
      hash = (53 * hash) + getFollowingList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.api.rpc.follow.GetFollowingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.api.rpc.follow.GetFollowingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetFollowingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetFollowingResponse)
      web.api.rpc.follow.GetFollowingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.api.rpc.follow.Follow.internal_static_GetFollowingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.api.rpc.follow.Follow.internal_static_GetFollowingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.api.rpc.follow.GetFollowingResponse.class, web.api.rpc.follow.GetFollowingResponse.Builder.class);
    }

    // Construct using web.api.rpc.follow.GetFollowingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      following_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.api.rpc.follow.Follow.internal_static_GetFollowingResponse_descriptor;
    }

    public web.api.rpc.follow.GetFollowingResponse getDefaultInstanceForType() {
      return web.api.rpc.follow.GetFollowingResponse.getDefaultInstance();
    }

    public web.api.rpc.follow.GetFollowingResponse build() {
      web.api.rpc.follow.GetFollowingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public web.api.rpc.follow.GetFollowingResponse buildPartial() {
      web.api.rpc.follow.GetFollowingResponse result = new web.api.rpc.follow.GetFollowingResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        following_ = following_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.following_ = following_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.api.rpc.follow.GetFollowingResponse) {
        return mergeFrom((web.api.rpc.follow.GetFollowingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(web.api.rpc.follow.GetFollowingResponse other) {
      if (other == web.api.rpc.follow.GetFollowingResponse.getDefaultInstance()) return this;
      if (!other.following_.isEmpty()) {
        if (following_.isEmpty()) {
          following_ = other.following_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFollowingIsMutable();
          following_.addAll(other.following_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.api.rpc.follow.GetFollowingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.api.rpc.follow.GetFollowingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList following_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFollowingIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        following_ = new com.google.protobuf.LazyStringArrayList(following_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFollowingList() {
      return following_.getUnmodifiableView();
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public int getFollowingCount() {
      return following_.size();
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public java.lang.String getFollowing(int index) {
      return following_.get(index);
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFollowingBytes(int index) {
      return following_.getByteString(index);
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public Builder setFollowing(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFollowingIsMutable();
      following_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public Builder addFollowing(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFollowingIsMutable();
      following_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public Builder addAllFollowing(
        java.lang.Iterable<java.lang.String> values) {
      ensureFollowingIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, following_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public Builder clearFollowing() {
      following_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string following = 1;</code>
     */
    public Builder addFollowingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFollowingIsMutable();
      following_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetFollowingResponse)
  }

  // @@protoc_insertion_point(class_scope:GetFollowingResponse)
  private static final web.api.rpc.follow.GetFollowingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.api.rpc.follow.GetFollowingResponse();
  }

  public static web.api.rpc.follow.GetFollowingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFollowingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetFollowingResponse>() {
    public GetFollowingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetFollowingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetFollowingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFollowingResponse> getParserForType() {
    return PARSER;
  }

  public web.api.rpc.follow.GetFollowingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

