// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.user.grpc;

public interface ConfirmEmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfirmEmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
