// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.user.grpc;

/**
 * Protobuf type {@code GetAllUserResponse}
 */
public  final class GetAllUserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllUserResponse)
    GetAllUserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllUserResponse.newBuilder() to construct.
  private GetAllUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllUserResponse() {
    allUser_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllUserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              allUser_ = new java.util.ArrayList<web.service.user.grpc.GetAllUserResponse.UserGrpcModel>();
              mutable_bitField0_ |= 0x00000001;
            }
            allUser_.add(
                input.readMessage(web.service.user.grpc.GetAllUserResponse.UserGrpcModel.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        allUser_ = java.util.Collections.unmodifiableList(allUser_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.service.user.grpc.User.internal_static_GetAllUserResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.service.user.grpc.User.internal_static_GetAllUserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.service.user.grpc.GetAllUserResponse.class, web.service.user.grpc.GetAllUserResponse.Builder.class);
  }

  public interface UserGrpcModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetAllUserResponse.UserGrpcModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();
  }
  /**
   * Protobuf type {@code GetAllUserResponse.UserGrpcModel}
   */
  public  static final class UserGrpcModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetAllUserResponse.UserGrpcModel)
      UserGrpcModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserGrpcModel.newBuilder() to construct.
    private UserGrpcModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGrpcModel() {
      id_ = "";
      firstName_ = "";
      lastName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserGrpcModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.user.grpc.User.internal_static_GetAllUserResponse_UserGrpcModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.user.grpc.User.internal_static_GetAllUserResponse_UserGrpcModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.user.grpc.GetAllUserResponse.UserGrpcModel.class, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof web.service.user.grpc.GetAllUserResponse.UserGrpcModel)) {
        return super.equals(obj);
      }
      web.service.user.grpc.GetAllUserResponse.UserGrpcModel other = (web.service.user.grpc.GetAllUserResponse.UserGrpcModel) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(web.service.user.grpc.GetAllUserResponse.UserGrpcModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetAllUserResponse.UserGrpcModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetAllUserResponse.UserGrpcModel)
        web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return web.service.user.grpc.User.internal_static_GetAllUserResponse_UserGrpcModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return web.service.user.grpc.User.internal_static_GetAllUserResponse_UserGrpcModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                web.service.user.grpc.GetAllUserResponse.UserGrpcModel.class, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder.class);
      }

      // Construct using web.service.user.grpc.GetAllUserResponse.UserGrpcModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        firstName_ = "";

        lastName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return web.service.user.grpc.User.internal_static_GetAllUserResponse_UserGrpcModel_descriptor;
      }

      public web.service.user.grpc.GetAllUserResponse.UserGrpcModel getDefaultInstanceForType() {
        return web.service.user.grpc.GetAllUserResponse.UserGrpcModel.getDefaultInstance();
      }

      public web.service.user.grpc.GetAllUserResponse.UserGrpcModel build() {
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public web.service.user.grpc.GetAllUserResponse.UserGrpcModel buildPartial() {
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel result = new web.service.user.grpc.GetAllUserResponse.UserGrpcModel(this);
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof web.service.user.grpc.GetAllUserResponse.UserGrpcModel) {
          return mergeFrom((web.service.user.grpc.GetAllUserResponse.UserGrpcModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(web.service.user.grpc.GetAllUserResponse.UserGrpcModel other) {
        if (other == web.service.user.grpc.GetAllUserResponse.UserGrpcModel.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (web.service.user.grpc.GetAllUserResponse.UserGrpcModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetAllUserResponse.UserGrpcModel)
    }

    // @@protoc_insertion_point(class_scope:GetAllUserResponse.UserGrpcModel)
    private static final web.service.user.grpc.GetAllUserResponse.UserGrpcModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new web.service.user.grpc.GetAllUserResponse.UserGrpcModel();
    }

    public static web.service.user.grpc.GetAllUserResponse.UserGrpcModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGrpcModel>
        PARSER = new com.google.protobuf.AbstractParser<UserGrpcModel>() {
      public UserGrpcModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserGrpcModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGrpcModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserGrpcModel> getParserForType() {
      return PARSER;
    }

    public web.service.user.grpc.GetAllUserResponse.UserGrpcModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ALLUSER_FIELD_NUMBER = 1;
  private java.util.List<web.service.user.grpc.GetAllUserResponse.UserGrpcModel> allUser_;
  /**
   * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
   */
  public java.util.List<web.service.user.grpc.GetAllUserResponse.UserGrpcModel> getAllUserList() {
    return allUser_;
  }
  /**
   * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
   */
  public java.util.List<? extends web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder> 
      getAllUserOrBuilderList() {
    return allUser_;
  }
  /**
   * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
   */
  public int getAllUserCount() {
    return allUser_.size();
  }
  /**
   * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
   */
  public web.service.user.grpc.GetAllUserResponse.UserGrpcModel getAllUser(int index) {
    return allUser_.get(index);
  }
  /**
   * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
   */
  public web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder getAllUserOrBuilder(
      int index) {
    return allUser_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < allUser_.size(); i++) {
      output.writeMessage(1, allUser_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < allUser_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, allUser_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.service.user.grpc.GetAllUserResponse)) {
      return super.equals(obj);
    }
    web.service.user.grpc.GetAllUserResponse other = (web.service.user.grpc.GetAllUserResponse) obj;

    boolean result = true;
    result = result && getAllUserList()
        .equals(other.getAllUserList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAllUserCount() > 0) {
      hash = (37 * hash) + ALLUSER_FIELD_NUMBER;
      hash = (53 * hash) + getAllUserList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.user.grpc.GetAllUserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.service.user.grpc.GetAllUserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.user.grpc.GetAllUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.service.user.grpc.GetAllUserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllUserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllUserResponse)
      web.service.user.grpc.GetAllUserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.user.grpc.User.internal_static_GetAllUserResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.user.grpc.User.internal_static_GetAllUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.user.grpc.GetAllUserResponse.class, web.service.user.grpc.GetAllUserResponse.Builder.class);
    }

    // Construct using web.service.user.grpc.GetAllUserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAllUserFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (allUserBuilder_ == null) {
        allUser_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        allUserBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.service.user.grpc.User.internal_static_GetAllUserResponse_descriptor;
    }

    public web.service.user.grpc.GetAllUserResponse getDefaultInstanceForType() {
      return web.service.user.grpc.GetAllUserResponse.getDefaultInstance();
    }

    public web.service.user.grpc.GetAllUserResponse build() {
      web.service.user.grpc.GetAllUserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public web.service.user.grpc.GetAllUserResponse buildPartial() {
      web.service.user.grpc.GetAllUserResponse result = new web.service.user.grpc.GetAllUserResponse(this);
      int from_bitField0_ = bitField0_;
      if (allUserBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          allUser_ = java.util.Collections.unmodifiableList(allUser_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.allUser_ = allUser_;
      } else {
        result.allUser_ = allUserBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.service.user.grpc.GetAllUserResponse) {
        return mergeFrom((web.service.user.grpc.GetAllUserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(web.service.user.grpc.GetAllUserResponse other) {
      if (other == web.service.user.grpc.GetAllUserResponse.getDefaultInstance()) return this;
      if (allUserBuilder_ == null) {
        if (!other.allUser_.isEmpty()) {
          if (allUser_.isEmpty()) {
            allUser_ = other.allUser_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAllUserIsMutable();
            allUser_.addAll(other.allUser_);
          }
          onChanged();
        }
      } else {
        if (!other.allUser_.isEmpty()) {
          if (allUserBuilder_.isEmpty()) {
            allUserBuilder_.dispose();
            allUserBuilder_ = null;
            allUser_ = other.allUser_;
            bitField0_ = (bitField0_ & ~0x00000001);
            allUserBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAllUserFieldBuilder() : null;
          } else {
            allUserBuilder_.addAllMessages(other.allUser_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.service.user.grpc.GetAllUserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.service.user.grpc.GetAllUserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<web.service.user.grpc.GetAllUserResponse.UserGrpcModel> allUser_ =
      java.util.Collections.emptyList();
    private void ensureAllUserIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        allUser_ = new java.util.ArrayList<web.service.user.grpc.GetAllUserResponse.UserGrpcModel>(allUser_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder, web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder> allUserBuilder_;

    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public java.util.List<web.service.user.grpc.GetAllUserResponse.UserGrpcModel> getAllUserList() {
      if (allUserBuilder_ == null) {
        return java.util.Collections.unmodifiableList(allUser_);
      } else {
        return allUserBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public int getAllUserCount() {
      if (allUserBuilder_ == null) {
        return allUser_.size();
      } else {
        return allUserBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public web.service.user.grpc.GetAllUserResponse.UserGrpcModel getAllUser(int index) {
      if (allUserBuilder_ == null) {
        return allUser_.get(index);
      } else {
        return allUserBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder setAllUser(
        int index, web.service.user.grpc.GetAllUserResponse.UserGrpcModel value) {
      if (allUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllUserIsMutable();
        allUser_.set(index, value);
        onChanged();
      } else {
        allUserBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder setAllUser(
        int index, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder builderForValue) {
      if (allUserBuilder_ == null) {
        ensureAllUserIsMutable();
        allUser_.set(index, builderForValue.build());
        onChanged();
      } else {
        allUserBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder addAllUser(web.service.user.grpc.GetAllUserResponse.UserGrpcModel value) {
      if (allUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllUserIsMutable();
        allUser_.add(value);
        onChanged();
      } else {
        allUserBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder addAllUser(
        int index, web.service.user.grpc.GetAllUserResponse.UserGrpcModel value) {
      if (allUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllUserIsMutable();
        allUser_.add(index, value);
        onChanged();
      } else {
        allUserBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder addAllUser(
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder builderForValue) {
      if (allUserBuilder_ == null) {
        ensureAllUserIsMutable();
        allUser_.add(builderForValue.build());
        onChanged();
      } else {
        allUserBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder addAllUser(
        int index, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder builderForValue) {
      if (allUserBuilder_ == null) {
        ensureAllUserIsMutable();
        allUser_.add(index, builderForValue.build());
        onChanged();
      } else {
        allUserBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder addAllAllUser(
        java.lang.Iterable<? extends web.service.user.grpc.GetAllUserResponse.UserGrpcModel> values) {
      if (allUserBuilder_ == null) {
        ensureAllUserIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allUser_);
        onChanged();
      } else {
        allUserBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder clearAllUser() {
      if (allUserBuilder_ == null) {
        allUser_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        allUserBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public Builder removeAllUser(int index) {
      if (allUserBuilder_ == null) {
        ensureAllUserIsMutable();
        allUser_.remove(index);
        onChanged();
      } else {
        allUserBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder getAllUserBuilder(
        int index) {
      return getAllUserFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder getAllUserOrBuilder(
        int index) {
      if (allUserBuilder_ == null) {
        return allUser_.get(index);  } else {
        return allUserBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public java.util.List<? extends web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder> 
         getAllUserOrBuilderList() {
      if (allUserBuilder_ != null) {
        return allUserBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(allUser_);
      }
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder addAllUserBuilder() {
      return getAllUserFieldBuilder().addBuilder(
          web.service.user.grpc.GetAllUserResponse.UserGrpcModel.getDefaultInstance());
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder addAllUserBuilder(
        int index) {
      return getAllUserFieldBuilder().addBuilder(
          index, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.getDefaultInstance());
    }
    /**
     * <code>repeated .GetAllUserResponse.UserGrpcModel allUser = 1;</code>
     */
    public java.util.List<web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder> 
         getAllUserBuilderList() {
      return getAllUserFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.user.grpc.GetAllUserResponse.UserGrpcModel, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder, web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder> 
        getAllUserFieldBuilder() {
      if (allUserBuilder_ == null) {
        allUserBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.user.grpc.GetAllUserResponse.UserGrpcModel, web.service.user.grpc.GetAllUserResponse.UserGrpcModel.Builder, web.service.user.grpc.GetAllUserResponse.UserGrpcModelOrBuilder>(
                allUser_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        allUser_ = null;
      }
      return allUserBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllUserResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllUserResponse)
  private static final web.service.user.grpc.GetAllUserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.service.user.grpc.GetAllUserResponse();
  }

  public static web.service.user.grpc.GetAllUserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllUserResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllUserResponse>() {
    public GetAllUserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllUserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllUserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllUserResponse> getParserForType() {
    return PARSER;
  }

  public web.service.user.grpc.GetAllUserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

