// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.user.grpc;

public interface GetAllUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();
}
