// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.user.grpc;

public interface GetUserAvatarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserAvatarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string avatar = 1;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 1;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
