// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.user.grpc;

public interface NewPasswordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewPasswordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string newPassword = 2;</code>
   */
  java.lang.String getNewPassword();
  /**
   * <code>string newPassword = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewPasswordBytes();

  /**
   * <code>string newPasswordConfirm = 3;</code>
   */
  java.lang.String getNewPasswordConfirm();
  /**
   * <code>string newPasswordConfirm = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewPasswordConfirmBytes();
}
